### ISSUE TITLE
Crashes with calc(...) is not a function in vite app

### ISSUE THREAD

**Issue by Mitsunee** [bulbacss/postcss-var-optimize#11]
I tried using this plugin in a vite project I just started (no published repo yet) and am getting this error:

```
[vite] Internal server error: calc(...) is not a function
  Plugin: vite:css
  File: /home/mitsu/ProjectPathHere/style.css?direct
      at /home/mitsu/ProjectPathHere/node_modules/postcss-var-optimize/index.js:103:11
      at LazyResult.runOnRoot (/home/mitsu/ProjectPathHere/node_modules/postcss/lib/lazy-result.js:339:16)
      at LazyResult.runAsync (/home/mitsu/ProjectPathHere/node_modules/postcss/lib/lazy-result.js:393:26)
      at async compileCSS (/home/mitsu/ProjectPathHere/node_modules/vite/dist/node/chunks/dep-f5552faa.js:20426:27)
      at async TransformContext.transform (/home/mitsu/ProjectPathHere/node_modules/vite/dist/node/chunks/dep-f5552faa.js:20015:50)
      at async Object.transform (/home/mitsu/ProjectPathHere/node_modules/vite/dist/node/chunks/dep-f5552faa.js:36985:30)
      at async doTransform (/home/mitsu/ProjectPathHere/node_modules/vite/dist/node/chunks/dep-f5552faa.js:52060:29)
```

**Versions:**

- postcss-var-optimize: 0.0.4
- postcss-calc: 8.2.2
- postcss: 8.4.5
- vite: 2.7.13

**Config:**

```js
// postcss.config.cjs
const plugins = {
  "postcss-import": {},
  "postcss-nested": {},
  "postcss-var-optimize": {},
  "postcss-preset-env": {
    autoprefixer: {
      flexbox: "no-2009"
    },
    stage: 3,
    features: {
      "custom-properties": false
    }
  }
};

module.exports = {
  plugins
};
```

I tried changing my postcss config to be an es module, which broke other plugins. I am also seeing a warning about `postcss.plugin` being deprecated before vite clears the cli.

**Comment by Tofandel** [comment]
Sorry, I missed this issue

You have a conflicting versions set, which npm or yarn should have warned you about

The postcss-calc dependency requires ^7 and you're using version 8, which hasn't yet been upgraded

**Comment by Tofandel** [comment]
Just published v8.0.0 of the plugin which supports postcss8
